# Generated by Django 3.2.5 on 2021-07-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='tax_jurid',
            field=models.CharField(default='p i g e', max_length=18),
        ),
        migrations.AlterField(
            model_name='country',
            name='tax_physic',
            field=models.CharField(default='d z', max_length=11),
        ),
        migrations.AlterField(
            model_name='savecountry',
            name='tax_jurid',
            field=models.CharField(default='p i g e', max_length=18),
        ),
        migrations.AlterField(
            model_name='savecountry',
            name='tax_physic',
            field=models.CharField(default='d z', max_length=11),
        ),
    ]
