# Generated by Django 3.2.5 on 2021-09-12 17:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startgame',
            name='save_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 17, 29, 38, 977864, tzinfo=utc)),
        ),
    ]
