# Generated by Django 3.2.8 on 2021-12-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='capital',
            field=models.CharField(default='Default city', max_length=30),
        ),
        migrations.AlterField(
            model_name='regions',
            name='name',
            field=models.CharField(default='Default region', max_length=30),
        ),
        migrations.AlterField(
            model_name='saveregions',
            name='capital',
            field=models.CharField(default='Default city', max_length=30),
        ),
        migrations.AlterField(
            model_name='saveregions',
            name='name',
            field=models.CharField(default='Default region', max_length=30),
        ),
    ]
