# Generated by Django 3.2.5 on 2021-07-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210702_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='tax_jurid',
            field=models.CharField(default='p i g e', max_length=22),
        ),
        migrations.AlterField(
            model_name='savecountry',
            name='tax_jurid',
            field=models.CharField(default='p i g e', max_length=22),
        ),
    ]
