# Generated by Django 3.2.8 on 2021-12-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20211222_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='Default country', max_length=30),
        ),
        migrations.AlterField(
            model_name='savecountry',
            name='name',
            field=models.CharField(default='Default country', max_length=30),
        ),
    ]
