# Generated by Django 3.2.5 on 2021-09-12 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_startgame_save_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startgame',
            name='save_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
