# Generated by Django 3.2.5 on 2021-09-12 17:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_startgame_save_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startgame',
            name='save_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 17, 34, 9, 901651, tzinfo=utc)),
        ),
    ]
