# Generated by Django 3.2.5 on 2021-07-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210702_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savecontracts',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='con_type',
            field=models.CharField(choices=[('AL', 'Alliance'), ('CM', 'Common market'), ('CT', 'Culture transfer'), ('SH', 'Social help'), ('EH', 'Economic help'), ('PA', 'Passage of army'), ('ES', 'Economic sanctions'), ('DW', 'Declare war'), ('CP', 'Contract of Peace'), ('FW', 'Finish war'), ('VC', 'Vassal country')], default='EH', max_length=2),
        ),
        migrations.AlterField(
            model_name='savecontracts',
            name='con_type',
            field=models.CharField(choices=[('AL', 'Alliance'), ('CM', 'Common market'), ('CT', 'Culture transfer'), ('SH', 'Social help'), ('EH', 'Economic help'), ('PA', 'Passage of army'), ('ES', 'Economic sanctions'), ('DW', 'Declare war'), ('CP', 'Contract of Peace'), ('FW', 'Finish war'), ('VC', 'Vassal country')], default='EH', max_length=2),
        ),
    ]
