# Generated by Django 4.0 on 2022-01-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20211222_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savecountryai',
            name='name',
            field=models.CharField(default='Default country', max_length=30),
        ),
    ]
