# Generated by Django 3.2.5 on 2021-07-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210705_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='priority',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='savecontracts',
            name='priority',
            field=models.CharField(default='', max_length=30),
        ),
    ]
