# Generated by Django 3.2.5 on 2021-09-12 17:36

import App.models_saves
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_startgame_save_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startgame',
            name='save_date',
            field=models.DateTimeField(default=App.models_saves.getTime),
        ),
    ]
