# Generated by Django 3.2.5 on 2021-07-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210705_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='savesquad',
            name='place',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='savesquadai',
            name='place',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='squad',
            name='place',
            field=models.CharField(default='', max_length=30),
        ),
    ]
