# Generated by Django 3.2.8 on 2021-12-15 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_startgame_save_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='allowance_disability',
        ),
        migrations.RemoveField(
            model_name='country',
            name='education_avail',
        ),
        migrations.RemoveField(
            model_name='country',
            name='maternal_capital',
        ),
        migrations.RemoveField(
            model_name='countrybonus',
            name='aqueducs',
        ),
        migrations.RemoveField(
            model_name='countrybonus',
            name='pave_road',
        ),
        migrations.RemoveField(
            model_name='countrybonus',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='countrybonus',
            name='universities',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='aqueducs',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='area',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='pave_road',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='universities',
        ),
        migrations.RemoveField(
            model_name='savecountry',
            name='allowance_disability',
        ),
        migrations.RemoveField(
            model_name='savecountry',
            name='education_avail',
        ),
        migrations.RemoveField(
            model_name='savecountry',
            name='maternal_capital',
        ),
        migrations.RemoveField(
            model_name='saveregions',
            name='aqueducs',
        ),
        migrations.RemoveField(
            model_name='saveregions',
            name='area',
        ),
        migrations.RemoveField(
            model_name='saveregions',
            name='pave_road',
        ),
        migrations.RemoveField(
            model_name='saveregions',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='saveregions',
            name='universities',
        ),
        migrations.AlterField(
            model_name='startgame',
            name='save_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
