# Generated by Django 3.2.5 on 2021-07-18 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20210712_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=1)),
                ('actions', models.IntegerField(default=10)),
                ('support', models.FloatField(default=0)),
                ('stability', models.FloatField(default=0)),
                ('population', models.FloatField(default=0)),
                ('inflation', models.FloatField(default=0)),
                ('poverty', models.FloatField(default=0)),
                ('unemployment', models.FloatField(default=0)),
                ('avg_salary', models.FloatField(default=0)),
                ('infrastructure', models.FloatField(default=0)),
                ('stone_road', models.FloatField(default=0)),
                ('pave_road', models.FloatField(default=0)),
                ('trash', models.FloatField(default=0)),
                ('port', models.FloatField(default=0)),
                ('delivery_box', models.FloatField(default=0)),
                ('delivery_people', models.FloatField(default=0)),
                ('aqueduc', models.FloatField(default=0)),
                ('alchemy', models.FloatField(default=0)),
                ('magic', models.FloatField(default=0)),
                ('science', models.FloatField(default=0)),
                ('technology', models.FloatField(default=0)),
                ('education_quality', models.FloatField(default=0)),
                ('education_access', models.FloatField(default=0)),
                ('schools', models.FloatField(default=0)),
                ('universities', models.FloatField(default=0)),
                ('army_quality', models.FloatField(default=0)),
                ('industry_blackmetall', models.FloatField(default=0)),
                ('industry_colormetall', models.FloatField(default=0)),
                ('industry_coal', models.FloatField(default=0)),
                ('industry_hunting', models.FloatField(default=0)),
                ('industry_fishing', models.FloatField(default=0)),
                ('industry_forestry', models.FloatField(default=0)),
                ('industry_blacksmith', models.FloatField(default=0)),
                ('industry_animals', models.FloatField(default=0)),
                ('industry_vegetable', models.FloatField(default=0)),
                ('industry_wheat', models.FloatField(default=0)),
                ('industry_typography', models.FloatField(default=0)),
                ('industry_light', models.FloatField(default=0)),
                ('industry_eating', models.FloatField(default=0)),
                ('industry_jewelry', models.FloatField(default=0)),
                ('industry_transport', models.FloatField(default=0)),
                ('industry_alchemy', models.FloatField(default=0)),
                ('industry_hiring', models.FloatField(default=0)),
                ('industry_culture', models.FloatField(default=0)),
                ('industry_other', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='startgame',
            name='buffs',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='App.countrybonus'),
            preserve_default=False,
        ),
    ]
