# Generated by Django 3.2.5 on 2021-07-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20210718_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrybonus',
            name='budget_education',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='countrybonus',
            name='budget_government',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='countrybonus',
            name='budget_infrastructure',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='countrybonus',
            name='budget_propaganda',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='countrybonus',
            name='budget_research',
            field=models.FloatField(default=0.5),
        ),
    ]
