# Generated by Django 3.2.5 on 2021-07-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20210723_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrybonus',
            name='kazna',
            field=models.IntegerField(default=0),
        ),
    ]
