# Generated by Django 3.2.5 on 2021-07-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_countrybonus_kazna'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='occuped',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contracts',
            name='spends',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='savecontracts',
            name='occuped',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='savecontracts',
            name='spends',
            field=models.CharField(default='', max_length=25),
        ),
    ]
