# Generated by Django 3.2.5 on 2021-07-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20210729_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='spends',
            field=models.CharField(default='0_0', max_length=25),
        ),
        migrations.AlterField(
            model_name='savecontracts',
            name='spends',
            field=models.CharField(default='0_0', max_length=25),
        ),
    ]
