# Generated by Django 3.2.5 on 2021-08-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20210729_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrybonus',
            options={'verbose_name': 'Save Баффы', 'verbose_name_plural': 'Save Баффы'},
        ),
        migrations.RenameField(
            model_name='countrybonus',
            old_name='aqueduc',
            new_name='aqueducs',
        ),
    ]
