# Generated by Django 3.2.5 on 2021-08-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20210814_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrybonus',
            name='kazna',
            field=models.IntegerField(default=25000000),
        ),
    ]
