# Generated by Django 3.2.5 on 2021-08-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_countrybonus_kazna'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='deadline',
            field=models.IntegerField(default=99999),
        ),
        migrations.AddField(
            model_name='savecontracts',
            name='deadline',
            field=models.IntegerField(default=99999),
        ),
    ]
