# Generated by Django 3.2.5 on 2021-08-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20210818_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='con_type',
            field=models.CharField(choices=[('AL', 'Alliance'), ('CM', 'Common market'), ('PA', 'Passage of army'), ('CT', 'Culture transfer'), ('SH', 'Social help'), ('EH', 'Economic help'), ('CP', 'Contract of Peace'), ('ES', 'Economic sanctions'), ('DW', 'Declare war'), ('FW', 'Finish war'), ('VC', 'Vassal country')], default='EH', max_length=2),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='occuped',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='savecontracts',
            name='con_type',
            field=models.CharField(choices=[('AL', 'Alliance'), ('CM', 'Common market'), ('PA', 'Passage of army'), ('CT', 'Culture transfer'), ('SH', 'Social help'), ('EH', 'Economic help'), ('CP', 'Contract of Peace'), ('ES', 'Economic sanctions'), ('DW', 'Declare war'), ('FW', 'Finish war'), ('VC', 'Vassal country')], default='EH', max_length=2),
        ),
        migrations.AlterField(
            model_name='savecontracts',
            name='occuped',
            field=models.TextField(blank=True, default=''),
        ),
    ]
